import { calculatePlayerValue } from '../trade-logic.js';
import { FOOTBALL_ROSTER_CONFIG } from '../sports/footballRosterConfig.js';
const PREMIUM_POS = new Set(['QB', 'WR', 'OL', 'DL', 'CB']);
const num = (v, fb = 0) => Number.isFinite(Number(v)) ? Number(v) : fb;
const clamp = (v, min, max) => Math.max(min, Math.min(max, v));
const tierForValue = (v) => v >= 190 ? 'premium' : v >= 145 ? 'starter' : v >= 110 ? 'rotation' : v >= 80 ? 'depth' : 'low';
const safeValue = (p) => { try { return num(calculatePlayerValue(p), 0); } catch { return estimateTradeValue(p); } };
const estimateTradeValue = (p = {}) => Math.max(1, Math.round(((num(p.ovr,60)*1.1)+(num(p.potential,p.ovr)*0.8))*(PREMIUM_POS.has(p.pos)?1.15:1)*(num(p.age)<=24?1.15:num(p.age)>=31?0.8:1) - (String(p?.status??'').toLowerCase().includes('inj')?12:0) - (num(p?.contract?.baseAnnual)>=16?8:0)));
function getNeedMap(roster = [], cfg = FOOTBALL_ROSTER_CONFIG) { const map = {}; for (const pos of cfg.positionGroups) { const exp = cfg.groupConfig?.[pos]?.starterCountExpected ?? 1; const ps = roster.filter((p) => p.pos === pos).sort((a,b)=>num(b.ovr)-num(a.ovr)); const st = ps.slice(0, exp); const avg = st.length ? st.reduce((s,p)=>s+num(p.ovr),0)/st.length : 0; const miss = Math.max(0, exp-st.length); const score = clamp(Math.round((78-avg)+(miss*25)),0,100); map[pos] = { pos, needLevel: score>=55?'urgent':score>=35?'thin':'stable', needScore: score, reason: miss>0?`${miss} starter slot(s) missing.`:`Starter quality ${Math.round(avg)} OVR.`, recommendedTargetType: score>=55?'starter_upgrade':score>=35?'depth_patch':'luxury' }; } return map; }
export function buildTradeFinderAnalysis({ userTeam, teams = [], userRoster = [], leaguePlayers = [], cap = {}, footballConfig = FOOTBALL_ROSTER_CONFIG }) {
 const userTeamId = num(userTeam?.id,-1); const targetNeeds = Object.values(getNeedMap(userRoster, footballConfig)).sort((a,b)=>b.needScore-a.needScore).slice(0,6);
 const userSurplus=[]; const chips=[];
 for (const pos of footballConfig.positionGroups){const exp=footballConfig.groupConfig?.[pos]?.starterCountExpected??1; const ps=userRoster.filter((p)=>p.pos===pos).sort((a,b)=>num(b.ovr)-num(a.ovr)); const depth=ps.slice(exp); const score=clamp((depth.length*22)+(num(depth[0]?.ovr)-68),0,100); if(score<25) continue; const posChips=depth.filter((p)=>num(p.ovr)>=66).map((p)=>{const v=safeValue(p); const sal=num(p?.contract?.baseAnnual,null); const rf=[]; if(num(p.age)>=30) rf.push('aging_curve'); if(sal!=null&&sal>=14) rf.push('high_salary'); if(num(p.schemeFit,60)<50) rf.push('low_scheme_fit'); return { playerId:p.id,name:p.name,pos:p.pos,age:p.age,ovr:p.ovr,potential:p.potential??p.ovr,salary:sal,baseAnnual:sal,yearsRemaining:num(p?.contract?.yearsRemaining??p?.contract?.years,0),schemeFit:p.schemeFit,valueScore:v,valueTier:tierForValue(v),reason:'Depth/surplus at position makes this a movable asset.',riskFlags:rf};}); const best=posChips.sort((a,b)=>b.valueScore-a.valueScore)[0]??null; userSurplus.push({pos,surplusScore:score,reason:`Depth behind ${exp} starter(s).`,players:ps.map((p)=>p.id),bestTradeChip:best}); chips.push(...posChips); }
 const chipPool=chips.sort((a,b)=>b.valueScore-a.valueScore); const ideas=[]; const urgent=targetNeeds.filter((n)=>n.needLevel!=='stable'); const rankedNeeds = (urgent.length ? urgent : targetNeeds.slice(0, 3));
 for(const need of rankedNeeds){const cands=leaguePlayers.filter((p)=>num(p.teamId)!==userTeamId&&num(p.teamId,-1)>=0&&p.pos===need.pos).sort((a,b)=>safeValue(b)-safeValue(a)).slice(0,5); if(!cands.length) continue; for(const t of cands){const tv=safeValue(t); const out=chipPool.find((c)=>c.pos===t.pos&&c.valueScore>=tv*0.6)??chipPool.find((c)=>c.valueScore>=tv*0.75)??chipPool[0]; if(!out) continue; const delta=Math.round(tv-out.valueScore); const match=delta<=25?'fair':delta<=75?'expensive':'unrealistic'; const inSal=num(t?.contract?.baseAnnual,null); const outSal=num(userRoster.find((p)=>p.id===out.playerId)?.contract?.baseAnnual,null); const capImpact=inSal==null||outSal==null?null:Number((outSal-inSal).toFixed(1)); const role=num(t.age)<=24&&num(t.potential,t.ovr)-num(t.ovr)>=5?'youth_upside':need.needLevel==='urgent'&&num(t.ovr)>=78?'starter_upgrade':num(t.ovr)>=72?'depth_patch':'luxury'; const fit=clamp(Math.round((need.needScore*0.45)+((100-Math.abs(delta))*0.25)+(role==='starter_upgrade'?20:role==='youth_upside'?14:8)+(capImpact==null?3:capImpact>0?8:-6)),1,99); const rf=[]; if(num(t.age)>=31) rf.push('aging_curve'); if(num(t?.contract?.baseAnnual)>=16) rf.push('high_salary'); if(num(t.schemeFit,60)<50) rf.push('low_scheme_fit'); ideas.push({id:`${need.pos}-${t.teamId}-${t.id}-${out.playerId}`,targetPlayerId:t.id,targetPlayerName:t.name,targetTeamId:t.teamId,targetTeamAbbr:teams.find((x)=>num(x.id)===num(t.teamId))?.abbr??`T${t.teamId}`,targetPos:t.pos,targetAge:t.age,targetOVR:t.ovr,targetPotential:t.potential??t.ovr,targetSalary:inSal??undefined,targetValue:tv,outgoingPlayerIds:[out.playerId],outgoingSummary:`${out.pos} ${out.name}`,outgoingValue:out.valueScore,valueDelta:delta,valueMatch:match,capImpact,capImpactLabel:capImpact==null?'cap impact unknown':capImpact>=0?`cap relief +$${capImpact}M`:`cap cost $${Math.abs(capImpact)}M`,roleFit:role,needFitTag:need.needLevel==='urgent'?'urgent_need':'team_need',riskFlags:rf,fitScore:fit,recommendation:match==='unrealistic'?'avoid':fit>=75?'pursue':fit>=62?'consider':'watch',reason:`Possible framework to address ${need.pos} with ${t.name}.`}); }}
 const tradeIdeas=ideas.filter((i)=>num(i.targetTeamId)!==userTeamId).sort((a,b)=>b.fitScore-a.fitScore).slice(0,15);
 return { summary:{ biggestNeed:targetNeeds[0]??null,strongestSurplus:userSurplus.sort((a,b)=>b.surplusScore-a.surplusScore)[0]??null,bestTradeChip:chipPool[0]??null,topTarget:tradeIdeas[0]??null,capWarning:cap?.capRoom!=null&&num(cap.capRoom)<0?'Over cap: prioritize cap-neutral frameworks.':null }, userSurplus, userTradeChips:chipPool.slice(0,10), targetNeeds, tradeIdeas, filters:['all','team_need','starter_upgrade','depth_patch','cap_relief','youth_upside','fair_value','avoid_risks'] };
}
