import { afterEach, describe, expect, it, vi } from 'vitest';
import {
  processPlayerProgression,
  resolveSchemeMultiplier,
} from '../progression-logic.js';
import { normalizeTeamStaff } from '../staff/staffPhilosophy.js';
import { getDevelopmentRateModifier } from '../coaching-philosophy-effects.js';
import { Utils } from '../utils.js';

// Wrap getDevelopmentRateModifier so we can inspect the exact staff object the
// progression pass forwards to it, while still exercising the real helper.
vi.mock('../coaching-philosophy-effects.js', async (importOriginal) => {
  const actual = await importOriginal();
  return {
    ...actual,
    getDevelopmentRateModifier: vi.fn(actual.getDevelopmentRateModifier),
  };
});

// Neutral personality so the breakout/bust probability terms zero out and the
// growth roll stays predictable (mirrors coaching-dev-modifier-wiring.test.js).
function buildProfile() {
  return {
    workEthic: 55, leadership: 55, diva: 45, riskTaker: 40,
    discipline: 45, coachability: 60, holdoutRisk: 20, consistency: 65, offFieldRisk: 25,
  };
}

function buildPlayer(overrides = {}) {
  return {
    id: 1,
    name: 'Norm Test QB',
    teamId: 1,
    pos: 'QB',
    age: 23,
    ovr: 75,
    potential: 85,
    devTrait: 'Normal',
    morale: 70,
    personalityProfile: buildProfile(),
    ratings: {
      throwPower: 75, throwAccuracy: 75, accuracyShort: 75,
      accuracyMedium: 75, accuracyDeep: 75, awareness: 75,
      intelligence: 75, speed: 75, agility: 75, acceleration: 75,
    },
    ...overrides,
  };
}

// A raw, un-normalized live staff record as generated by the staff system:
// lowercase trait, `schemePreference` string, `overall` (not `overallRating`).
function rawLiveStaff() {
  return {
    headCoach: { traits: ['developmental'], schemePreference: 'Spread', overall: 85 },
    offCoordinator: { schemePreference: 'Spread' },
  };
}

afterEach(() => {
  vi.restoreAllMocks();
  vi.mocked(getDevelopmentRateModifier).mockClear();
});

// ── resolveSchemeMultiplier reads the canonical live staff source ──────────────

describe('resolveSchemeMultiplier live-staff fallback', () => {
  it('falls back to team.staff head coach when team.coach is absent', () => {
    // Fresh leagues populate team.staff (schemePreference/overall) but not
    // team.coach — scheme fit must still resolve from the live staff.
    const team = { staff: { headCoach: { schemePreference: 'Spread', overall: 85 } } };
    // QB fits a SPREAD offense → coach-quality tier for overall 85 → 1.08
    expect(resolveSchemeMultiplier({ pos: 'QB' }, team)).toBe(1.08);
    // RB does not fit SPREAD → misfit penalty
    expect(resolveSchemeMultiplier({ pos: 'RB' }, team)).toBe(0.90);
  });

  it('reads an explicitly-passed normalized staff record (teamCoaches entry)', () => {
    const staff = normalizeTeamStaff({ staff: { headCoach: { schemePreference: 'Spread', overall: 85 } } });
    expect(resolveSchemeMultiplier({ pos: 'QB' }, null, staff)).toBe(1.08);
    expect(resolveSchemeMultiplier({ pos: 'RB' }, null, staff)).toBe(0.90);
  });

  it('the Coaching Carousel V1 record still wins over live staff when present', () => {
    const team = {
      coach: { headCoach: { scheme: 'POWER_RUN', overallRating: 85 } },
      staff: { headCoach: { schemePreference: 'Spread', overall: 85 } },
    };
    // Carousel POWER_RUN makes a QB a misfit; the SPREAD staff must not override it.
    expect(resolveSchemeMultiplier({ pos: 'QB' }, team)).toBe(0.90);
  });

  it('defensive players are unaffected by an offensive-only staff philosophy', () => {
    const team = { staff: { headCoach: { schemePreference: 'Spread', overall: 85 } } };
    // CB is a defensive player; the HC has no defensive scheme (BALANCED) → no misfit.
    expect(resolveSchemeMultiplier({ pos: 'CB' }, team)).toBe(1.08);
  });

  it('legacy raw staff without normalized philosophy fields resolves safely', () => {
    // Only schemePreference present; resolver normalizes a copy internally.
    const staff = { headCoach: { schemePreference: 'Smashmouth', overall: 45 } };
    // POWER_RUN (inferred from Smashmouth) fits an RB → coach-quality tier (45 → 0.88)
    expect(resolveSchemeMultiplier({ pos: 'RB' }, { staff })).toBe(0.88);
    // ...and makes a QB a misfit.
    expect(resolveSchemeMultiplier({ pos: 'QB' }, { staff })).toBe(0.90);
  });

  it('returns 1.0 when neither coach nor staff head coach exists', () => {
    expect(resolveSchemeMultiplier({ pos: 'QB' }, {})).toBe(1.0);
    expect(resolveSchemeMultiplier({ pos: 'QB' }, { staff: {} })).toBe(1.0);
    expect(resolveSchemeMultiplier({ pos: 'QB' }, { staff: { headCoach: null } })).toBe(1.0);
    expect(resolveSchemeMultiplier({ pos: 'QB' }, null)).toBe(1.0);
  });
});

// ── getDevelopmentRateModifier receives normalized staff fields ────────────────

describe('processPlayerProgression forwards normalized staff to the dev modifier', () => {
  it('the staff normalized by the orchestrator reaches getDevelopmentRateModifier', () => {
    vi.spyOn(Utils, 'random').mockReturnValue(0.5);
    vi.spyOn(Utils, 'rand').mockImplementation((min, max) => max);

    // Replicate the worker orchestrator: teamCoaches[id] = normalizeTeamStaff(team).
    const rawTeam = { id: 1, staff: rawLiveStaff() };
    const teamCoaches = { 1: normalizeTeamStaff(rawTeam) };

    processPlayerProgression([buildPlayer()], { teamCoaches, teams: {} });

    expect(getDevelopmentRateModifier).toHaveBeenCalled();
    const [, headCoachArg, staffArg] = vi.mocked(getDevelopmentRateModifier).mock.calls[0];
    // Trait was lowercased in the raw record; normalization uppercases it so the
    // helper's DEVELOPMENTAL check fires.
    expect(headCoachArg.traits).toContain('DEVELOPMENTAL');
    expect(headCoachArg.offensivePhilosophy).toBe('SPREAD');
    expect(staffArg.offCoordinator.offensivePhilosophy).toBe('SPREAD');
  });

  it('normalized staff yields a higher dev modifier than raw un-normalized staff', () => {
    const raw = rawLiveStaff();
    const normalized = normalizeTeamStaff({ staff: raw });
    // Raw lowercase trait fails the DEVELOPMENTAL check; normalized picks up the +5%.
    const rawMod = getDevelopmentRateModifier('QB', raw.headCoach, raw);
    const normMod = getDevelopmentRateModifier('QB', normalized.headCoach, normalized);
    expect(normMod).toBeGreaterThan(rawMod);
  });
});

// ── Safety: missing / malformed staff never crashes ───────────────────────────

describe('progression staff normalization safety', () => {
  it('null, empty, and missing staff entries progress without throwing', () => {
    vi.spyOn(Utils, 'random').mockReturnValue(0.5);
    vi.spyOn(Utils, 'rand').mockImplementation((min, max) => max);

    const nullStaff  = buildPlayer({ id: 40, teamId: 40 });
    const emptyStaff = buildPlayer({ id: 41, teamId: 41 });
    const noEntry    = buildPlayer({ id: 42, teamId: 42 });

    expect(() =>
      processPlayerProgression([nullStaff, emptyStaff, noEntry], {
        teamCoaches: { 40: null, 41: {} },
        teams: { 40: { staff: null }, 41: { staff: {} } },
      })
    ).not.toThrow();

    // All three fall back to a 1.0 scheme multiplier → identical nudges.
    expect(nullStaff.ratings.throwPower).toBe(emptyStaff.ratings.throwPower);
    expect(nullStaff.ratings.throwPower).toBe(noEntry.ratings.throwPower);
  });

  it('a missing team.staff head coach is treated as a no-op scheme multiplier', () => {
    expect(resolveSchemeMultiplier({ pos: 'QB' }, { staff: undefined })).toBe(1.0);
  });

  it('is deterministic across identical runs with normalized staff', () => {
    function makeLCG(seed) {
      let s = seed >>> 0 || 1;
      return () => {
        s = ((1664525 * s + 1013904223) | 0) >>> 0;
        return s / 0x100000000;
      };
    }

    function runOnce() {
      const next = makeLCG(4242);
      vi.spyOn(Utils, 'random').mockImplementation(next);
      vi.spyOn(Utils, 'rand').mockImplementation((min, max) => Math.floor(next() * (max - min + 1)) + min);

      const teamCoaches = { 1: normalizeTeamStaff({ id: 1, staff: rawLiveStaff() }) };
      const players = [
        buildPlayer({ id: 1, teamId: 1 }),
        buildPlayer({ id: 2, teamId: 1, age: 27, devTrait: 'Star' }),
      ];
      processPlayerProgression(players, { teamCoaches, teams: {} });
      vi.restoreAllMocks();
      return players.map((p) => ({ ovr: p.ovr, ratings: { ...p.ratings } }));
    }

    expect(runOnce()).toEqual(runOnce());
  });
});
