import React, { useRef, useState } from "react";
import OwnerMessagesCard from "./OwnerMessagesCard.jsx";

const ADVISOR_TOPICS = [
  { key: "roster", label: "👥 Roster Advice" },
  { key: "trade", label: "🔄 Should I Trade?" },
  { key: "draft", label: "🎓 Draft Strategy" },
  { key: "cap", label: "💰 Cap Space" },
  { key: "gameplan", label: "🏈 This Week Gameplan" },
  { key: "rebuild", label: "🏗️ Rebuild vs Win Now" },
];

export default function GMAdvisor({ league, leagueState, currentSeason, currentWeek }) {
  const resolvedLeague = leagueState ?? league;
  const [topic, setTopic] = useState(null);
  const [advice, setAdvice] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const responseRef = useRef(null);
  const userTeam =
    resolvedLeague?.teams?.find((t) => t?.isUserTeam === true || t?.id === resolvedLeague?.userTeamId) ??
    null;

  const buildContext = (selectedTopic) => {
    if (!leagueState) {
      return `You are a GM advisor for a football simulation game.
    Team reports are still coming in from scouts and cap staff.
    Give practical, in-universe strategy guidance for topic: ${selectedTopic}.
    Keep it grounded and forward-looking.`;
    }

    const teams = Array.isArray(leagueState?.teams) ? leagueState.teams : [];
    const selectedUserTeam = teams.find((t) => t?.isUserTeam === true) ?? teams[0] ?? null;

    if (!selectedUserTeam) {
      return `You are a GM advisor for a football simulation game.
    Team-specific reports are unavailable right now.
    Give balanced strategy advice for topic: ${selectedTopic} using league-level principles.`;
    }

    const roster = Array.isArray(selectedUserTeam?.roster) ? selectedUserTeam.roster : [];
    const safeRoster =
      roster.length > 0
        ? roster
        : [{ name: "Depth chart update pending", position: "N/A", ovr: 0, age: 0 }];

    const topPlayers = [...safeRoster]
      .sort((a, b) => (b?.ovr ?? 0) - (a?.ovr ?? 0))
      .slice(0, 15)
      .map(
        (p) =>
          `${p?.name ?? "Unknown"} (${p?.position ?? p?.pos ?? "?"}, OVR:${p?.ovr ?? 0}, Age:${p?.age ?? 0})`,
      )
      .join("\n  ");

    const onBlock =
      safeRoster
        .filter((p) => p?.onTradeBlock === true)
        .map((p) => `${p?.name ?? "Unknown"} (${p?.position ?? p?.pos ?? "?"}, OVR:${p?.ovr ?? 0})`)
        .join(", ") || "None";

    const capUsed = safeRoster
      .reduce((sum, p) => sum + (p?.contract?.salary ?? 2), 0)
      .toFixed(1);
    const capSpace = (200 - parseFloat(capUsed)).toFixed(1);

    const wins = selectedUserTeam?.wins ?? 0;
    const losses = selectedUserTeam?.losses ?? 0;

    const positionGroups = {};
    safeRoster.forEach((p) => {
      const pos = p?.position ?? p?.pos ?? "UNK";
      if (!positionGroups[pos]) positionGroups[pos] = [];
      positionGroups[pos].push(p?.ovr ?? 0);
    });
    const weakPositions =
      Object.entries(positionGroups)
        .filter(([, ovrs]) => Math.max(...ovrs) < 75)
        .map(([pos]) => pos)
        .join(", ") || "None identified";

    const picks = Array.isArray(leagueState?.draftPicks)
      ? leagueState.draftPicks
          .filter((p) => p?.currentOwner === selectedUserTeam?.id)
          .map((p) => `Round ${p?.round} (${p?.season})`)
          .join(", ") || "None"
      : "Unknown";

    return `
IMPORTANT: You are an AI advisor inside a FICTIONAL football 
simulation video game called Football GM Sim. 

DO NOT use any real NFL knowledge, real player statistics, 
or real team history. The team names may match real NFL teams 
but ALL players, stats, contracts, and records below are 
FICTIONAL simulation data generated by the game engine.

Base ALL advice ONLY on the exact data provided below.
Reference specific player names from the roster below.
Never mention real NFL players or real NFL events.

=== SIMULATION GAME STATE ===

Team: ${selectedUserTeam?.name ?? "Unknown Team"} (FICTIONAL SIM TEAM)
Season: ${currentSeason ?? leagueState?.year ?? resolvedLeague?.year ?? "—"} | Week: ${currentWeek ?? leagueState?.week ?? resolvedLeague?.week ?? "—"}
Record: ${wins}W - ${losses}L
Salary Cap Used: $${capUsed}M of $200M
Cap Space Remaining: $${capSpace}M
Dead Cap: $${(selectedUserTeam?.deadCap ?? 0).toFixed(1)}M

TOP 15 PLAYERS (fictional sim players):
  ${topPlayers || "No roster data yet"}

PLAYERS ON TRADE BLOCK:
  ${onBlock}

WEAK POSITIONS (no starter above OVR 75):
  ${weakPositions}

DRAFT PICKS OWNED:
  ${picks}

COACHING SCHEME:
  Offense: ${selectedUserTeam?.offScheme ?? "Unknown"}
  Defense: ${selectedUserTeam?.defScheme ?? "Unknown"}

Fan Approval: ${selectedUserTeam?.fanApproval ?? 50}/100

=== USER QUESTION ===
Topic: ${selectedTopic}

Give specific, actionable advice based ONLY on the fictional 
sim data above. Name specific players from the roster above.
Use bullet points. Maximum 180 words. 
Do not reference any real NFL events or real players.
  `.trim();
  };

  const handleAsk = async (selectedTopic) => {
    setTopic(selectedTopic);
    setLoading(true);
    setAdvice("");
    setError("");

    try {
      const response = await fetch("/.netlify/functions/groq-proxy", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: "llama-3.3-70b-versatile",
          max_tokens: 400,
          temperature: 0.7,
          messages: [
            {
              role: "system",
              content: `You are an AI GM advisor inside a fictional 
              football simulation game called Football GM Sim. 
              
              CRITICAL RULES:
              1. ONLY use data provided in the user message
              2. NEVER use real NFL knowledge, real player names, 
                 or real team statistics
              3. All players, contracts, and records are fictional
              4. Always reference specific player names from the 
                 provided roster
              5. Be direct and strategic — max 180 words
              6. Use bullet points for recommendations`,
            },
            {
              role: "user",
              content: buildContext(selectedTopic),
            },
          ],
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        setError(`Advisor error: ${data?.error?.message ?? "Unknown error. Try again."}`);
        return;
      }

      const text = data?.choices?.[0]?.message?.content ?? "No advisory memo came through. Try another topic in a moment.";
      setAdvice(text);
      requestAnimationFrame(() => {
        responseRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
      });
    } catch (_err) {
      setError("The advisor line is quiet right now. Give it a moment and request another briefing.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="gm-advisor">
      <div className="advisor-header">
        <h2>🤖 GM Advisor</h2>
        <p className="advisor-sub">AI-powered strategy for your franchise</p>
      </div>

      <OwnerMessagesCard
        league={resolvedLeague}
        userTeam={userTeam}
        currentWeek={currentWeek ?? resolvedLeague?.week}
        currentSeason={currentSeason ?? resolvedLeague?.year}
      />

      <div className="advisor-topics">
        {ADVISOR_TOPICS.map((t) => (
          <button
            key={t.key}
            className={`topic-btn ${topic === t.key ? "active" : ""}`}
            onClick={() => handleAsk(t.key)}
            disabled={loading || !userTeam}
          >
            {t.label}
          </button>
        ))}
      </div>
      <p className="advisor-notice">⚡ Powered by Groq · AI advice based on your roster</p>

      <div className="advisor-response" ref={responseRef}>
        {loading && (
          <div className="advisor-loading">
            <span className="pulse">Analyzing your roster...</span>
          </div>
        )}
        {error && <p className="advisor-error">{error}</p>}
        {advice && !loading && (
          <div className="advisor-advice">
            <p className="advice-topic">Re: {ADVISOR_TOPICS.find((t) => t.key === topic)?.label}</p>
            <div className="advice-body">
              {advice.split("\n").map((line, i) => (
                <p key={i}>{line}</p>
              ))}
            </div>
          </div>
        )}
        {!advice && !loading && !error && (
          <p className="advisor-prompt">
            {userTeam
              ? "Select a topic to request a strategy briefing for your football operations staff."
              : "Open an active franchise file to brief with your GM advisor."}
          </p>
        )}
      </div>
    </div>
  );
}
